# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\myGreatestwork\individual_inter_news.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsPixmapItem, QGraphicsScene

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, News, picture_dir):
        _translate = QtCore.QCoreApplication.translate
        self.News = News
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background-image: url(src/1.jpg);}")
        self.centralwidget.setObjectName("centralwidget")
        self.picture_dir = picture_dir
        
        self.newspicture = QtWidgets.QGraphicsView(self.centralwidget)
        self.newspicture.setGeometry(QtCore.QRect(60, 20, 490, 290))
        self.newspicture.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.newspicture.setObjectName("newspicture")
        self.newspicture.setStyleSheet("background-color:transparent; border:none;")
        frame = QImage(self.picture_dir+"/"+str(self.News.index)+".jpg")
        pix = QPixmap.fromImage(frame)
        item = QGraphicsPixmapItem(pix)
        scene = QGraphicsScene()
        scene.addItem(item)
        self.newspicture.setScene(scene)
        
        self.title = QtWidgets.QTextBrowser(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(575, 40, 575, 100))
        self.title.setStyleSheet("background-color: transparent; border:none\n"
"")
        self.title.setTabStopWidth(90)
        self.title.setObjectName("title")
        
        self.empty1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.empty1.setGeometry(QtCore.QRect(50, 310, 1100, 480))
        self.empty1.setObjectName("empty1")
        self.empty1.setStyleSheet("background-color: rgba(255, 255, 255, 180); border:none\n")
        self.empty2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.empty2.setGeometry(QtCore.QRect(50, 10, 1100, 300))
        self.empty2.setObjectName("empty2")
        self.empty2.setStyleSheet("background-color: rgba(255, 255, 255, 180); border:none\n")
        
        self.brief = QtWidgets.QTextBrowser(self.centralwidget)
        self.brief.setGeometry(QtCore.QRect(575, 150, 575, 180))
        self.brief.setObjectName("brief")
        self.brief.setStyleSheet("background-color: transparent;border:none\n")
        
        self.details = QtWidgets.QListWidget(self.centralwidget)
        self.details.setGeometry(QtCore.QRect(70, 330, 1060, 440))
        self.details.setTextElideMode(QtCore.Qt.ElideLeft)
        self.details.setWordWrap(True)
        self.details.setObjectName("details")
        self.details.setStyleSheet("background-color: transparent;border:none\n")
        for detail in self.News.details:
                item = QtWidgets.QListWidgetItem()
                item.setText(_translate("MainWindow", detail))
                font = QtGui.QFont()
                font.setFamily("微软雅黑")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(75)
                item.setFont(font)
                self.details.addItem(item)
        
        self.newsurl = QtWidgets.QTextBrowser(self.centralwidget)
        self.newsurl.setGeometry(QtCore.QRect(170, 770, 871, 51))
        self.newsurl.setObjectName("newsurl")
        self.newsurl.setStyleSheet("background-color: transparent;border:none")
        
        self.newspicture.raise_()
        self.title.raise_()
        self.details.raise_()
        self.brief.raise_()
        self.newsurl.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        # 如果标题字数过多就缩小字号
        if len(self.News.title) <=32:
                self.title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Bold\'; font-size:20pt; font-weight:600;\">"+self.News.title+"</span></p></body></html>"))
        else:
                self.title.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Bold\'; font-size:14pt; font-weight:800;\">"+self.News.title+"</span></p></body></html>"))
        
        self.empty1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        
        # 如果brief字数过多就缩小字号
        if len(self.News.brief) <= 90:
                self.brief.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFangSC-Regular\',\'Helvetica\',\'Arial\',\'Microsoft Yahei\',\'sans-serif\'; font-size:14pt; font-weight:600; \">"+self.News.brief+"</span></p></body></html>"))
        else:
                self.brief.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PingFangSC-Regular\',\'Helvetica\',\'Arial\',\'Microsoft Yahei\',\'sans-serif\'; font-size:12pt; font-weight:600; \">"+self.News.brief+"</span></p></body></html>")) 
        
        
        self.newsurl.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">"+self.News.url+"</span></p></body></html>"))
        