# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\myGreatestwork\international_news.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, gotInterNews):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 766)
        self.gotInterNews = gotInterNews
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background-image: url(src/1.jpg);}")
        self.centralwidget.setObjectName("centralwidget")
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 50, 1241, 691))
        self.listWidget.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.listWidget.setAutoScrollMargin(16)
        self.listWidget.setIconSize(QtCore.QSize(200, 200))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setBatchSize(101)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        
        _translate = QtCore.QCoreApplication.translate
        for news in self.gotInterNews:
            count = 1
            item = QtWidgets.QListWidgetItem()
            font = QtGui.QFont()
            font.setFamily("微软雅黑")
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            item.setFont(font)
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("international_pictures/"+str(news.index)+".jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
            item.setIcon(icon)
            brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 127))
            brush.setStyle(QtCore.Qt.NoBrush)
            item.setBackground(brush)
            item.setText(_translate("MainWindow", news.title))
            self.listWidget.addItem(item)
            count += 1
        self.listWidget.itemClicked.connect(self.getIndividualNews)
        
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 181, 41))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.textBrowser.setObjectName("textBrowser")
        self.returnBack = QtWidgets.QPushButton(self.centralwidget)
        self.returnBack.setGeometry(QtCore.QRect(190, 10, 71, 31))
        self.returnBack.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.returnBack.setObjectName("returnback")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">国际要闻</span></p></body></html>"))
        self.returnBack.setText(_translate("MainWindow", "返回"))

    def getIndividualNews(self):
        import Ui_individual_news
        currentIndex = self.listWidget.currentIndex().row()
        self.mainWindow = QMainWindow()
        individualNewsWindow = Ui_individual_news.Ui_MainWindow()
        individualNewsWindow.setupUi(self.mainWindow, self.gotInterNews[currentIndex], "international_pictures")
        self.mainWindow.show()
