# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\myGreatestwork\individual_magzine.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsPixmapItem, QGraphicsScene
from PyQt5.QtCore import QRectF


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, book, bookdir):
        _translate = QtCore.QCoreApplication.translate
        self.book = book
        self.bookdir = bookdir
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("#centralwidget{background-image: url(src/1.jpg);}")
        
        self.empty_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.empty_textBrowser.setGeometry(QtCore.QRect(30, 30, 1131, 721))
        self.empty_textBrowser.setObjectName("empty_textBrowser")
        self.empty_textBrowser.setStyleSheet("background-color:rgba(255,255,255,180); border:none;")
        
        self.bookpicture = QtWidgets.QGraphicsView(self.centralwidget)
        self.bookpicture.setGeometry(QtCore.QRect(50, 60, 161, 231))
        self.bookpicture.setObjectName("graphicsView")
        self.bookpicture.setStyleSheet("background-color:transparent; border:none;")
        frame = QImage(self.bookdir+"/"+str(self.book.index)+".jpg")
        pix = QPixmap.fromImage(frame)
        item = QGraphicsPixmapItem(pix)
        scene = QGraphicsScene()
        scene.addItem(item)
        self.bookpicture.setScene(scene)
        # self.bookpicture.fitInView(item)
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 340, 411, 401))
        self.listWidget.setIconSize(QtCore.QSize(100, 0))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setStyleSheet("background-color:transparent; border: none")
        for paragraph in book.author_info:
                item = QtWidgets.QListWidgetItem()
                item.setText(_translate("MainWindow", paragraph))
                font = QtGui.QFont()
                font.setFamily("微软雅黑")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(75)
                item.setFont(font)
                self.listWidget.addItem(item)
        
        
        self.autorIntro = QtWidgets.QTextBrowser(self.centralwidget)
        self.autorIntro.setGeometry(QtCore.QRect(50, 310, 151, 31))
        self.autorIntro.setObjectName("textBrowser_2")
        self.autorIntro.setStyleSheet("background-color:transparent; border:none;")
        
        self.bookTitle = QtWidgets.QTextBrowser(self.centralwidget)
        self.bookTitle.setGeometry(QtCore.QRect(220, 60, 481, 51))
        self.bookTitle.setObjectName("booktitle")
        self.bookTitle.setStyleSheet("background-color:transparent; border:none;")
        
        self.bookDate = QtWidgets.QTextBrowser(self.centralwidget)
        self.bookDate.setGeometry(QtCore.QRect(220, 170, 231, 21))
        self.bookDate.setObjectName("bookdate")
        self.bookDate.setStyleSheet("background-color:transparent; border:none;")
        
        self.bookPublisher = QtWidgets.QTextBrowser(self.centralwidget)
        self.bookPublisher.setGeometry(QtCore.QRect(220, 200, 231, 21))
        self.bookPublisher.setObjectName("bookpublisher")
        self.bookPublisher.setStyleSheet("background-color:transparent; border:none;")
        
        self.listWidget2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget2.setGeometry(QtCore.QRect(520, 160, 621, 581))
        self.listWidget2.setObjectName("listWidget2")
        self.listWidget2.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget2.setWordWrap(True)
        self.listWidget2.setStyleSheet("background-color:transparent; border: none")
        for paragraph in book.abstract:
                item = QtWidgets.QListWidgetItem()
                item.setText(_translate("MainWindow", paragraph))
                font = QtGui.QFont()
                font.setFamily("微软雅黑")
                font.setPointSize(12)
                font.setBold(False)
                font.setWeight(75)
                item.setFont(font)
                self.listWidget2.addItem(item)
        
        
        self.bookAbstract = QtWidgets.QTextBrowser(self.centralwidget)
        self.bookAbstract.setGeometry(QtCore.QRect(520, 120, 231, 31))
        self.bookAbstract.setObjectName("bookabstract")
        self.bookAbstract.setStyleSheet("background-color:transparent; border:none;")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        
        
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.autorIntro.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Bold\';font-size:14pt; font-weight:600;\">作家简介</span></p></body></html>"))
        self.bookTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Bold\'; font-size:16pt;\">"+self.book.title+"</span></p></body></html>"))
        self.bookDate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Regular\'; font-size:9pt;\">"+self.book.year+"</p></body></html>"))
        self.bookPublisher.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Regular\'; font-size:9pt;\">"+self.book.publisher+"</p></body></html>"))
        self.bookAbstract.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Bold\'; font-size:14pt; font-weight:600;\">图书简介</span></p></body></html>"))
