# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\myGreatestwork\magzines.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
import settings
import threading
import getMagzines
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, gotMagzines):
        self.gotMagzines = gotMagzines
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background-image: url("+"src/1.jpg"+");}")
        self.centralwidget.setObjectName("centralwidget")
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 30, 1081, 711))
        self.listWidget.setIconSize(QtCore.QSize(300, 300))
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.listWidget.setSpacing(30)
        
        for gotMagzine in self.gotMagzines:
            item = QtWidgets.QListWidgetItem()
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(gotMagzine.magzine_cover_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            item.setIcon(icon)
            self.listWidget.addItem(item)
        self.listWidget.itemClicked.connect(self.openMazine)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        
    def openMazine(self):
        currentIndex = self.listWidget.currentIndex().row()
        splits = self.gotMagzines[currentIndex].magzine_path.split('/')
        os.startfile(os.path.join(os.getcwd(), splits[0], splits[1]))
