# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\myGreatestwork\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, userSettings):
        
        # MainWindow初始化
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 602)
        MainWindow.setStyleSheet("#centralwidget{background-image: url(src/1.jpg);}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        
        self.userSettings = userSettings
        
        # centralwidget初始化
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # calendar初始化
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(550, 240, 491, 331))
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setObjectName("calendarWidget")
        self.calenderShowedStatus = True
        
        # calender收起的button
        self.calenderFold = QtWidgets.QPushButton(self.centralwidget)
        self.calenderFold.setGeometry(QtCore.QRect(970, 240, 41, 28))
        self.calenderFold.setStyleSheet("background-color: rgb(0, 67, 212);")
        self.calenderFold.setObjectName("pushButton")
        self.calenderFold.clicked.connect(self.clickCalenderFold)
        
        # internatinalNews初始化
        self.internatinalNews = QtWidgets.QTextBrowser(self.centralwidget)
        self.internatinalNews.setGeometry(QtCore.QRect(0, 0, 291, 241))
        self.internatinalNews.setStyleSheet("background-color: rgba(230, 227, 194, 128);")
        self.internatinalNews.setObjectName("internatinalNews")
        self.interShowedStatus = True
        
        # 查看internatinalNews完整内容的button
        self.internationalButton = QtWidgets.QPushButton(self.centralwidget)
        self.internationalButton.setGeometry(QtCore.QRect(180, 240, 111, 28))
        self.internationalButton.setStyleSheet("background-color: rgba(230, 224, 210, 128);")
        self.internationalButton.setObjectName("internationalButton")
        self.internationalButton.clicked.connect(self.clickInterContent)
        
        # 折叠internatinalNews
        self.internationalFold = QtWidgets.QPushButton(self.centralwidget)
        self.internationalFold.setGeometry(QtCore.QRect(190, 0, 93, 28))
        self.internationalFold.setStyleSheet("background-color: rgba(230, 224, 210, 128);")
        self.internationalFold.setObjectName("internationalFold")
        self.internationalFold.clicked.connect(self.clickInterFold)
        
        # newbooks初始化
        self.newbooks = QtWidgets.QTextBrowser(self.centralwidget)
        self.newbooks.setGeometry(QtCore.QRect(310, 0, 231, 241))
        self.newbooks.setStyleSheet("background-color: rgba(217, 221, 233, 128);")
        self.newbooks.setObjectName("newbooks")
        self.booksShowedStatus = True
        
        # 查看books完整内容的button
        self.booksButton = QtWidgets.QPushButton(self.centralwidget)
        self.booksButton.setGeometry(QtCore.QRect(420, 240, 111, 28))
        self.booksButton.setStyleSheet("background-color: rgba(220, 217, 233, 128);")
        self.booksButton.setObjectName("booksButton")
        self.booksButton.clicked.connect(self.clickBooksContent)
        
        # 折叠books
        self.booksFold = QtWidgets.QPushButton(self.centralwidget)
        self.booksFold.setGeometry(QtCore.QRect(440, 0, 93, 28))
        self.booksFold.setStyleSheet("background-color: rgba(220, 217, 233, 128);")
        self.booksFold.setObjectName("booksFold")
        self.booksFold.clicked.connect(self.clickBooksFold)
        
        # nationalnews初始化
        self.nationalNews = QtWidgets.QTextBrowser(self.centralwidget)
        self.nationalNews.setGeometry(QtCore.QRect(0, 270, 291, 281))
        self.nationalNews.setStyleSheet("background-color: rgba(163, 205, 221, 128);")
        self.nationalNews.setObjectName("nationalNews")
        self.nationShowedStatus = True
        
        # 查看nationalnews完整内容的button
        self.nationalButton = QtWidgets.QPushButton(self.centralwidget)
        self.nationalButton.setGeometry(QtCore.QRect(180, 550, 111, 28))
        self.nationalButton.setStyleSheet("background-color: rgba(163, 196, 221, 128);")
        self.nationalButton.setObjectName("nationalButton")
        self.nationalButton.clicked.connect(self.clickNationContent)
        
        # 折叠nationalnews
        self.nationalfold = QtWidgets.QPushButton(self.centralwidget)
        self.nationalfold.setGeometry(QtCore.QRect(190, 270, 93, 28))
        self.nationalfold.setStyleSheet("background-color: rgba(163, 196, 221, 128);")
        self.nationalfold.setObjectName("nationalfold")
        self.nationalfold.clicked.connect(self.clickNationFold)
        
        # magzines初始化
        self.magzines = QtWidgets.QTextBrowser(self.centralwidget)
        self.magzines.setGeometry(QtCore.QRect(580, 0, 461, 231))
        self.magzines.setStyleSheet("background-color: rgba(230, 227, 194, 128);")
        self.magzines.setObjectName("magzines")
        self.magzinesShowedStatus = True
        
        # 提醒magzines是否更新
        self.magzinesalert = QtWidgets.QTextBrowser(self.centralwidget)
        self.magzinesalert.setGeometry(QtCore.QRect(550, 0, 31, 221))
        self.magzinesalert.setStyleSheet("background-color: rgba(169, 170, 191, 128);border-left-color: rgb(169, 170, 191);border:none;")
        self.magzinesalert.setObjectName("magzinesalert")
        
        # 查看magzines完整内容的button
        self.magzinesbutton = QtWidgets.QPushButton(self.centralwidget)
        self.magzinesbutton.setGeometry(QtCore.QRect(800, 0, 111, 28))
        self.magzinesbutton.setStyleSheet("background-color: rgba(230, 234, 203, 128);")
        self.magzinesbutton.setObjectName("magzinesbutton")
        self.magzinesbutton.clicked.connect(self.clickMagzinesContent)
        
        # 折叠magzines
        self.magzinesfold = QtWidgets.QPushButton(self.centralwidget)
        self.magzinesfold.setGeometry(QtCore.QRect(940, 0, 93, 28))
        self.magzinesfold.setStyleSheet("background-color: rgba(230, 234, 203, 128);")
        self.magzinesfold.setObjectName("magzinesfold")
        self.magzinesfold.clicked.connect(self.clickMagzinesFold)
        
        # magzine简图1
        self.magzine1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.magzine1.setGeometry(QtCore.QRect(590, 51, 101, 171))
        self.magzine1.setAutoFillBackground(False)
        if userSettings.gotMagzinesNums > 0:
            self.magzine1.setStyleSheet("border-image: url("+userSettings.gotMagzines[0].magzine_cover_path+");")
        self.magzine1.setObjectName("magzine1")
        
        # magzine简图2
        self.magzine2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.magzine2.setGeometry(QtCore.QRect(700, 50, 101, 171))
        self.magzine2.setAutoFillBackground(False)
        if userSettings.gotMagzinesNums > 1:
            self.magzine2.setStyleSheet("border-image: url("+userSettings.gotMagzines[1].magzine_cover_path+");")
        self.magzine2.setObjectName("magzine2")
        
        # magzine简图3
        self.magzine3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.magzine3.setGeometry(QtCore.QRect(810, 50, 101, 171))
        self.magzine3.setAutoFillBackground(False)
        if userSettings.gotMagzinesNums > 2:
            self.magzine3.setStyleSheet("border-image: url("+userSettings.gotMagzines[2].magzine_cover_path+");")
        self.magzine3.setObjectName("magzine3")
        
        # magzine简图4
        self.magzine4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.magzine4.setGeometry(QtCore.QRect(920, 50, 101, 171))
        self.magzine4.setAutoFillBackground(False)
        if userSettings.gotMagzinesNums > 3:
            self.magzine4.setStyleSheet("border-image: url("+userSettings.gotMagzines[3].magzine_cover_path+");")
        self.magzine4.setObjectName("magzine4")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow, userSettings)
        self.clickCalenderFold()
        self.clickInterFold()
        self.clickNationFold()
        self.clickBooksFold()
        self.clickMagzinesFold()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, userSettings):
        _translate = QtCore.QCoreApplication.translate
        
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        self.internatinalNews.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN Regular\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:600;\">最新国际资讯</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\"></span></p></body></html>"))
        
        self.internationalButton.setText(_translate("MainWindow", "查看完整资讯"))
        
        self.newbooks.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">上新好书</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"></span></p></body></html>"))
        
        self.booksButton.setText(_translate("MainWindow", "查看完整内容"))
        
        self.nationalNews.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">最新国内资讯</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"></span></p></body></html>"))
        
        self.nationalButton.setText(_translate("MainWindow", "查看完整资讯"))
        
        self.magzines.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">最新外刊</span></p></body></html>"))
        
        if userSettings.isMagzinesUpdated:
            self.magzinesalert.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
    "p, li { white-space: pre-wrap; }\n"
    "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">您的外刊更新了！</span></p></body></html>"))
        else:
            self.magzinesalert.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
    "p, li { white-space: pre-wrap; }\n"
    "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">您有外刊还未读完！</span></p></body></html>"))
        
        self.magzinesbutton.setText(_translate("MainWindow", "查看完整内容"))
        
        self.internationalFold.setText(_translate("MainWindow", "折叠"))
        
        self.nationalfold.setText(_translate("MainWindow", "折叠"))
        
        self.booksFold.setText(_translate("MainWindow", "折叠"))
        
        self.magzinesfold.setText(_translate("MainWindow", "折叠"))
        
        self.calenderFold.setText(_translate("MainWindow", "收起"))

    def clickInterFold(self):
        _translate = QtCore.QCoreApplication.translate
        if self.interShowedStatus:
            self.internatinalNews.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN Regular\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:600;\">最新国际资讯</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\"></span></p></body></html>"))
            self.internatinalNews.setStyleSheet("background-color: transparent;border:none;")
            self.internatinalNews.setContentsMargins(0,0,0,0)
            self.internationalFold.setStyleSheet("background-color: transparent;")
            self.internationalFold.setText(_translate("MainWindow", "展开"))
            self.internationalButton.hide()
            self.interShowedStatus = False
        else:
            interNewsAbstract = ""
            if self.userSettings.gotInterNewsNums < 4:
                for interNews in self.userSettings.gotInterNews:
                    interNewsAbstract+= interNews.title+'。     '
            else:
                for i in range(0,4):
                    interNewsAbstract+= self.userSettings.gotInterNews[i].title+'。     '
                    
            self.internatinalNews.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN Regular\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:600;\">最新国际资讯</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Regular\'; font-size:10pt;\">"+interNewsAbstract+"</span></p></body></html>"))
            self.internatinalNews.setStyleSheet("background-color: rgba(230, 227, 194, 128);")
            self.internationalFold.setStyleSheet("background-color: rgba(230, 224, 210, 128);")
            self.internationalFold.setText(_translate("MainWindow", "折叠"))
            self.internationalButton.show()
            self.interShowedStatus = True
    
    def clickInterContent(self):
        import Ui_international_news
        self.mainWindow = QMainWindow()
        self.interContentWindow = Ui_international_news.Ui_MainWindow()
        self.interContentWindow.setupUi(self.mainWindow, self.userSettings.gotInterNews)
        self.mainWindow.show()
    
    def clickNationFold(self):
        _translate = QtCore.QCoreApplication.translate
        if self.nationShowedStatus:
            self.nationalNews.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">最新国内资讯</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"></span></p></body></html>"))
            self.nationalNews.setStyleSheet("background-color: transparent;border:none;")
            self.nationalNews.setContentsMargins(0,0,0,0)
            self.nationalfold.setStyleSheet("background-color: transparent;")
            self.nationalfold.setText(_translate("MainWindow", "展开"))
            self.nationalButton.hide()
            self.nationShowedStatus = False
        else:
            nationNewsAbstract = ""
            if self.userSettings.gotNationNewsNums["brief"] < 4:
                for nationNews in self.userSettings.gotNationNews["brief"]:
                    nationNewsAbstract+= nationNews.title+'。       '
            else:
                for i in range(0,4):
                    nationNewsAbstract+= self.userSettings.gotNationNews["brief"][i].title+'。      '
            
            self.nationalNews.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">最新国内资讯</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Regular\'; font-size:10pt;\">"+nationNewsAbstract+"</span></p></body></html>"))
            self.nationalNews.setStyleSheet("background-color: rgba(163, 205, 221, 128);")
            self.nationalfold.setStyleSheet("background-color: rgba(163, 196, 221, 128);")
            self.nationalfold.setText(_translate("MainWindow", "折叠"))
            self.nationalButton.show()
            self.nationShowedStatus = True
    
    def clickNationContent(self):
        import Ui_national_news
        self.mainWindow = QMainWindow()
        self.nationContentWindow = Ui_national_news.Ui_MainWindow()
        self.nationContentWindow.setupUi(self.mainWindow, self.userSettings.gotNationNews, "brief")
        self.mainWindow.show()
    
    def clickBooksFold(self):
        _translate = QtCore.QCoreApplication.translate
        if self.booksShowedStatus:
            self.newbooks.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">上新好书</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"></span></p></body></html>"))
            self.newbooks.setStyleSheet("background-color: transparent;border:none;")
            self.newbooks.setContentsMargins(0,0,0,0)
            self.booksFold.setStyleSheet("background-color: transparent;")
            self.booksFold.setText(_translate("MainWindow", "展开"))
            self.booksButton.hide()
            self.booksShowedStatus = False
        else:
            booksAbstract = ""
            if self.userSettings.gotBooksNums < 4:
                for book in self.userSettings.gotBooks:
                    booksAbstract += book.title+' ['+book.author+']         '
            else:
                for i in range(0,4):
                    book = self.userSettings.gotBooks[i]
                    booksAbstract += book.title+' ['+book.author+']         '
                    
            self.newbooks.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">上新好书</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'思源黑体 CN Regular\'; font-size:10pt;\">"+booksAbstract+"</span></p></body></html>"))
            self.newbooks.setStyleSheet("background-color: rgba(217, 221, 233, 128);")
            self.booksFold.setStyleSheet("background-color: rgba(220, 217, 233, 128);")
            self.booksFold.setText(_translate("MainWindow", "折叠"))
            self.booksButton.show()
            self.booksShowedStatus = True
    
    def clickBooksContent(self):
        import Ui_books
        self.mainWindow = QMainWindow()
        self.interContentWindow = Ui_books.Ui_MainWindow()
        self.interContentWindow.setupUi(self.mainWindow, self.userSettings.gotBooks, self.userSettings.books_img_path) 
        self.mainWindow.show()
    
    def clickMagzinesFold(self):
        _translate = QtCore.QCoreApplication.translate 
        if self.magzinesShowedStatus:
            self.magzine1.hide()
            self.magzine2.hide()
            self.magzine3.hide()
            self.magzine4.hide()
            self.magzinesbutton.hide()
            self.magzines.setStyleSheet("background-color: transparent;border:none;")
            self.magzines.setContentsMargins(0,0,0,0)
            self.magzinesfold.setStyleSheet("background-color: transparent;")
            self.magzinesfold.setText(_translate("MainWindow", "展开"))    
            self.magzinesShowedStatus = False
        else:
            self.magzines.setStyleSheet("background-color: rgba(230, 227, 194, 128);")
            self.magzinesfold.setStyleSheet("background-color: rgba(230, 234, 203, 128);")
            self.magzinesfold.setText(_translate("MainWindow", "折叠"))
            self.magzine1.show()
            self.magzine2.show()
            self.magzine3.show()
            self.magzine4.show()
            self.magzinesbutton.show()
            self.magzinesShowedStatus = True
    
    def clickMagzinesContent(self):
        import Ui_magzines
        self.mainWindow = QMainWindow()
        self.nationContentWindow = Ui_magzines.Ui_MainWindow()
        self.nationContentWindow.setupUi(self.mainWindow, self.userSettings.gotMagzines)
        self.mainWindow.show()
    
    def clickCalenderFold(self):
        _translate = QtCore.QCoreApplication.translate
        if self.calenderShowedStatus:
            self.calendarWidget.hide()
            self.calenderFold.setText(_translate("MainWindow", "展开"))
            self.calenderFold.setStyleSheet("background-color: transparent;")
            self.calenderShowedStatus = False
        else:
            self.calendarWidget.show()
            self.calenderFold.setText(_translate("MainWindow", "收起"))
            self.calenderFold.setStyleSheet("background-color: rgba(0, 67, 212, 128);")
            self.calenderShowedStatus = True
     